config/routes.rb
GestionBase::Application.routes.draw do

   resources :articles do
      collection {post :import} 
      collection {get :example} 
   end
   resources :orders do 
         get :autocomplete_article_name, :on => :collection
   end
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :categories
      resources :equipment
      resources :makes
      resources :suppliers
      resources :locations
      resources :customers do
         collection do
            get 'find/:id' => 'customers#find', as: :store
         end
      end
      resources :invoices do

         get "payments/index"
         get "cancelar" => "invoices#cancelar_invoice"
         get "update_invoice" => "invoices#update_invoice"
      end
      devise_for :users
      resources :users
      get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
      get '', to: redirect("/#{I18n.default_locale}")
      get "models" => "models#index"
   end

   authenticated :user do
      root :to => 'customers#index'
   end
   unauthenticated :user do
      devise_scope :user do
         get "/" => "devise/sessions#new"
      end
   end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  CATEGORY= %w[HOGAR EMPRESA]
  INVOICE = %w[A B C]
  PHONES_COUNT_MIN = 0


scope :con_nombre, ->(nombre){where("LOWER(lastname) LIKE ?", "%#{nombre}%".downcase)}
scope :con_id, ->(id){ where('id = ?', "#{id}")}
scope :removed, ->(removed){ where('removed = ?', "#{removed}")}
  #Atributos
#  attr_accessible :address, :bar_code, :date_of_birth, :category, :cuit, :description, :dni, :email, :lastname, :name, :neighborhood, :reference_direction, :removed, :phones_attributes, :location_id,  :user_id, :invoice, :payments_attributes, :new_location

  attr_accessor :new_location

 
before_save :create_location


  #Relaciones
  has_many :phones, :dependent => :destroy
  has_many :loans
  has_many :ips
  has_many :payments
  belongs_to :user
  belongs_to :location
  has_many :accounts_receivable
  has_many :invoices
  #Validaciones
  validates :name, :lastname, :address,    presence: true
  validates :name, uniqueness: {scope: :lastname}, allow_nil: true, allow_blank: true
  validates :name, :lastname, :address,   :email, length: {maximum: 255}, allow_nil: true, allow_blank: true 
  validates :dni, length: {is: 8}, numericality: true, allow_blank: true
  validates :cuit, length: {is: 13}, allow_nil: true, allow_blank: true
  validates :email,  allow_nil: true, allow_blank: true, 
            :uniqueness => true
  #          :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
#  validates_date :date_of_birth, :before => lambda { 18.years.ago }
  validates_presence_of  :phones
 
 
#accepts_nested_attributes_for :phones, :reject_if => lambda {|a| a[:phone_number].blank? }, allow_destroy: true

 accepts_nested_attributes_for :phones, reject_if: :reject_phones, :allow_destroy => true
 accepts_nested_attributes_for :payments


 def self.search (q=nil)
     self.connection.execute(sanitize_sql(["SELECT * FROM customers"]))
 end

  def create_location

                self.location = Location.create!(name: new_location) if new_location.present?
  end 
 
 private
 def reject_phones(attribute)
       if phones.count > PHONES_COUNT_MIN 
          attribute[:phone_number].blank?
      end
 end


  

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json

		  require 'will_paginate/array'
		  before_filter :authenticate_user!, :except => [:some_action_without_auth]
load_and_authorize_resource :only =>[:show]

def find

    #@invoices = Invoice.find_by_customer_id(params[:id])
    @invoices = Invoice.invoices(params[:id])

      @payments = 0
      @invoices.each do |e|
         if e.cancelar_invoice == false
            @payments  += Payment.where('invoice_id = ?', e.id).sum(&:amount)
         end
      end

      @amount = Invoice.total_amount(params[:id]) 
      @total = @payments - @amount
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoices }
    end
end


def index
  @customers = Customer.all
   @customers = Customer.con_nombre(params[:q]) if params[:q].present?
   @customers = Customer.con_id(params[:customer_id]) if params[:customer_id].present?
  @customers = @customers.paginate(page: params[:page], per_page: 10)

  respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customers }
    end
  end

def show
    @customer = Customer.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new
  1.times {@customer.phones.build}    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
#    unauthorized! if cannot? :edit, @customer
  end

  # POST /customers
  # POST /customers.json
  def create
    #@customer = Customer.new(params[:customer].merge(:user_id => current_user.id))
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
  <div class="container"> 
    <div class="form-inputs">
      <div class="row-fluid">
  <%= f.error_notification %>
  <div class="span5">
     <%= f.input :name, :required=> true, :autofocus=>true, :input_html=> {class: 'form-control'} %>
    <%= f.input :lastname,   :required=> true, :hint => 'no special characteres' , :input_html=> {class: 'form-control'} %>
    <%= f.input :address,  :required=> true , :input_html=> {class: 'form-control'} %>
    <%= f.input :neighborhood , :input_html=> {class: 'form-control'} %>

    <div class="fields">
       <%= f.simple_fields_for :phones, :input_html=>{class: 'form-inline'} do |ph| %>
       <%=render 'phones', f: ph  %>
     <% end %>
  <%= link_to_add_fields t('view.customers.add_phones'), f , :phones %>
  </div>
  </div>

  <div class="span5">
    <%= f.input :email,  placeholder: 'user@domain.com', :input_html=> {class: 'form-control'} %>
    <%= f.input :dni, :input_html=> {class: 'form-control'} %>
          <%= f.input :location_id do %>
           <%= f.collection_select :location_id,  Location.order(:name), :id, :name, class: "span3" %>
           o Crear una <%=f.input :new_location , label: false, :input_html=> {class: 'form-control'} %>
   <% end  %>
   <%= f.input :description, :input_html => {:rows => 3, :class=> 'form-control'}%>
   <%= f.input :cuit, input_html: { class:'form-control'}  %>
   </div>
</div>
</div>
</div>
<div class="form-actions">
    <%= f.button  :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/customers/_phones.html.erb
<fieldset>
   <div class="form-group ">
      <%= f.label :phone_number, t('view.customers.phone_number')%>
      <div class="col-md-12">
         <div class="col-md-4">
            <%= f.select :phone, ["", "Casa", "Movil", "Trabajo"], {}, class: "select_i"%>
         </div>
         <div class="col-md-3">
             <%= f.text_field :phone_prefix, class: "form-control"  %>  
         </div>
         <div class="col-md-4">
            <%= f.text_field :phone_number, class: "form-control" %>
            <%= f.hidden_field :_destroy %>
         </div>
         <div class="col-md-1">
            <%= link_to  t('view.customers.remove_phone'), '#', class: "remove_fields" %>
         </div>
      </div>
   </div>
</fieldset>

app/views/customers/edit.html.erb
<% if flash[:error] %>
  <li class="alert alert-error"><%= flash[:error]  %></li>
  <% end %>
<% if notice %>
  <li class="alert alert-success"><%= notice  %></li>
  <% end %>

<div class="section_complete">
  <h3><%= t('customers.editing.title') %></h3>
  <div class="data">
      <%= render 'form' %>
  </div>
<%= link_to t('labels.show') , @customer %> |
<%= link_to t('labels.back'), customers_path %>
</div>

app/views/customers/find.html.erb
<h3>Listado de Remitos</h3>

<table class="table">
  <tr>
    <th>Remito</th>
    <th>Fecha</th>
    <th>Price total</th>
    <th>Pagado</th>
    <th>Total</th>
    <th>Cuenta corriente</th>
    <th>Estado Cta cte</th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.id %></td>
    <td><%= invoice.created_at.strftime("%d/%m/%Y") %></td>
    <td><%= invoice.price_total %></td>
    <td><%=  Invoice.sum_pay(invoice.id) %></td>
    <td></td>
    <td><%=  invoice.current_account ? 'Si' : 'No' %> </td>
    <td> <%= invoice.cancelar_invoice ? "  <b> 'Cancelado' </b> ": 'No Cancelado' if invoice.current_account == true %></td>
    <td><%= link_to "Editar", edit_invoice_path(invoice) %></td>
    <td><%= link_to "Imprimir", invoice_path( invoice, format: "pdf") %></td>
    <td><%= link_to "Cancelar", invoice_cancelar_path(invoice) %></td>
    <td><%= link_to "Actualizar precio",invoice_update_invoice_path( invoice) %></td>
    </tr>
<% end %>

        <tr>
                  <td></td>
                  <td></td>
                  <td><b><%= number_to_currency(@amount) %></b></td>
                  <td><b><%= number_to_currency(@payments) %></b></td>
                  <% if @total < 0 %>
                          <td class="alert alert-error"><b><%= number_to_currency(@total) %></b></td>
                  <% else %>
                  <td><b><%= number_to_currency(@total) %></b></td>
                  <% end %>
          </tr>
  </table>

<br />

app/views/customers/index.html.erb
<div class="row" >
   <div>
      <% if flash[:error] %>
         <div class="row-fluid span8">
         <li class="alert alert-error"><%= flash[:error]  %></li>
      </div>
   <% end %>
      <% if notice %>
         <li class="alert alert-success"><%= notice  %></li>
   <% end %>
   </div>

   <div class="span3 side">
      <%= simple_form_for '', method: 'get' do |f| %>
         <div class="search">
            <%= f.input( :q, label: 'Clientes', :input_html=> {
            class: 'form-control',
            data: {'autocomplete-field' => true,
                   'autocomplete-for' => '#_customer_id',
                   'autocomplete-url' => customers_path(format: :json)
         } 
         }) %>
      <%= f.input :customer_id, as: :hidden%>
      </div>
   <% end %> 
   </div>
   <div class="span8 section">
      <div class="title">
         <h2><%= t "customers.listing.title" %></h2>
      </div>
      <div  class="data">

         <%= will_paginate @customers %>
         <% if @customers %>
            <table class="table">
            <tr>
               <th><%= Customer.human_attribute_name(:lastname)   %></th>
               <th><%= Customer.human_attribute_name(:name)   %></th>
               <th><%= Customer.human_attribute_name(:address) %></th>
               <th><%= Customer.human_attribute_name(:neighborhood) %></th>
               <th><%= Customer.human_attribute_name(:description) %></th>
               <th></th>
               <th></th>
               <th></th>
               <th></th>
               <th></th>
            </tr>
            <% @customers.each do |customer| %>
               <tr>
               <td><%= customer.lastname %></td>
               <td><%= customer.name %></td>
               <td><%= customer.address %></td>
               <td><%= customer.neighborhood %></td>
               <td><%= customer.description %></td>
               <td><%= link_to t('labels.show'), customer %></td>
               <td><%= link_to t('labels.edit'), edit_customer_path(customer) %></td>
               <td><%= link_to 'Historial', store_customers_path(customer) %></td>
               <td><% link_to t('labels.destroy'), customer, method: :delete, data: { confirm: t('labels.are_you_sure') } %></td>
            </tr>
         <% end %>
         </table>
      <% end %>
      </div>
            <%= link_to "Nuevo Cliente", new_customer_path() %>
   </div>

app/views/customers/new.html.erb
<% if flash[:error] %>
  <li class="alert alert-error"><%= flash[:error]  %></li>
  <% end %>
<% if notice %>
  <li class="alert alert-success"><%= notice  %></li>
  <% end %>

<div class="section_complete">
  <h3><%= t ('customers.new.title') %></h3>
    <div class="data">
      <%= render 'form' %>
    </div>
</div>

app/views/customers/show.html.erb
<% if flash[:error] %>
  <li class="alert alert-error"><%= flash[:error] %></li>
  <% end %>
<% if notice %>
  <li class="alert alert-success"><%= notice %></li>
  <% end %>
<div class="Container span12">
<p>
  <b>Nombre:</b>
  <%= @customer.name %>
</p>

<p>
  <b>apellido:</b>
  <%= @customer.try(:lastname) %>
</p>

<p>
  <b>Direccion</b>
  <%= @customer.address %>
</p>

<p>
  <b>Localidad:</b>
</p>
<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Dni:</b>
  <%= @customer.dni %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @customer.description %>
</p>

<p>
  <b>Cuit:</b>
  <%= @customer.cuit %>
</p>

<p>
  <b>Telefono</b>
  <% @customer.phones.each do |u| %>
<%= u.phone_number %> -
<% end %>
</p>

<%= link_to 'Editar', edit_customer_path(@customer) %> |
<%= link_to 'Volver', customers_path %>

</div>