config/routes.rb
GestionBase::Application.routes.draw do

   resources :articles do
      collection {post :import} 
      collection {get :example} 
   end
   resources :orders do 
         get :autocomplete_article_name, :on => :collection
   end
   scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      resources :categories
      resources :equipment
      resources :makes
      resources :suppliers
      resources :locations
      resources :customers do
         collection do
            get 'find/:id' => 'customers#find', as: :store
         end
      end
      resources :invoices do

         get "payments/index"
         get "cancelar" => "invoices#cancelar_invoice"
         get "update_invoice" => "invoices#update_invoice"
      end
      devise_for :users
      resources :users
      get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
      get '', to: redirect("/#{I18n.default_locale}")
      get "models" => "models#index"
   end

   authenticated :user do
      root :to => 'customers#index'
   end
   unauthenticated :user do
      devise_scope :user do
         get "/" => "devise/sessions#new"
      end
   end

end

app/views/layouts/_footer.html.erb
<footer>
        <%= yield :scripts %>
        <div class="footer_app">
        </div>

  </footer>

app/views/layouts/_menu.html.erb
<div class="navbar navbar">
  <div class="navbar-inner">
      <!-- btn-navbar es el botón que reemplaza a los links ciuando la resolución es muy chica -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Marca o Logo -->
      <div class="nav-collapse">    
        <ul class="nav">
          <li class="dropdown"><%= link_to "Clientes", customers_path, "data-toogle"=>"dropdown", :class => "dropdown-toggle" %>
        </ul>
<% if current_user.role == "Admin" %>
        <ul class="nav">
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuración<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Localidades",locations_path%> </li>
            <li><%= link_to "Proovedores",suppliers_path%> </li>
             <li class="dropdown-submenu"> 
             <li><%= link_to "Marcas",makes_path%> </li>
             <li><%= link_to "Categorias",categories_path%> </li>
             </li>
            <li><%= link_to "Usuarios",users_path%> </li>
          </ul>
          </li>
  </ul>
  <% end %>
        <ul class="nav">
                      <li><%= link_to "Articulos",articles_path%> </li>
        
        </ul>
  
        <ul class="nav">
                      <li><%= link_to "Nuevo Remitos",new_invoice_path%> </li>
        </ul>

        <ul class="nav">
                      <li><%= link_to "Historial Remitos",invoices_path%> </li>
        </ul>
          <ul class="nav pull-right">
          <li><%= link_to current_user.email, edit_user_path(current_user.id) %></li><li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      </ul>


    </div>
  </div>
</div>

app/views/layouts/_menu2.html.erb
<nav class="navbar navbar-default" role="navigation">
     <div class="container-fluid">
       <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>

           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li class="dropdown"><%= link_to "Clientes", customers_path, "data-toogle"=>"dropdown", :class => "dropdown-toggle" %>
        </ul>
<% if current_user.role == "Admin" %>
        <ul class="nav navbar-nav">
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuración<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Localidades",locations_path%> </li>
            <li><%= link_to "Proovedores",suppliers_path%> </li>
             <li class="dropdown-submenu"> 
             <li><%= link_to "Marcas",makes_path%> </li>
             <li><%= link_to "Categorias",categories_path%> </li>
             </li>
            <li><%= link_to "Usuarios",users_path%> </li>
          </ul>
          </li>
  </ul>
  <% end %>
        <ul class="nav navbar-nav">
                      <li><%= link_to "Articulos",articles_path%> </li>
        
        </ul>
  
        <ul class="nav navbar-nav">
                      <li><%= link_to "Nuevo Remitos",new_invoice_path%> </li>
        </ul>

        <ul class="nav navbar-nav">
                      <li><%= link_to "Historial Remitos",invoices_path%> </li>
        </ul>
          <ul class="nav  navbar-nav pull-right">
          <li><%= link_to current_user.email, edit_user_path(current_user.id) %></li><li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      </ul>


           </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Sistema Gestion 1.0</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body>
        <%if user_signed_in?%>
          <%= render "layouts/menu2" %>
          <div>
            <%= yield %>
          </div>
          <%= render "layouts/footer" %>
        <% else %>
          <div class="container">
            <%= yield %>
          </div>
        <% end %>
  </body>
</html>